modify install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -172,8 +172,55 @@ function check_installed()
     }
 }
 
+# Sync repository
+sync_repo() {
+    local repo_uri="$1"
+    local repo_path="$2"
+    local repo_branch="$3"
+
+    if [ -z "$repo_branch" ]; then
+        repo_branch="master"
+    fi
+
+    if [ ! -e "$repo_path" ]; then
+        mkdir -p "$repo_path"
+        git clone --depth 1 --branch $repo_branch "https://github.com/$repo_uri.git" "$repo_path"
+    else
+        cd "$repo_path" && git pull --rebase --stat origin $repo_branch; cd - >/dev/null
+    fi
+}
+
+sync_brew_package() {
+    if ! command -v brew >/dev/null 2>&1; then
+        echo "Error: brew is not installed" >&2
+        return 1
+    fi
+
+    if ! command -v ${1} >/dev/null 2>&1; then
+        brew install ${1} >/dev/null
+    else
+        brew upgrade ${1} >/dev/null
+    fi
+}
+
 # Check git
 check_installed git
+
+# FZF
+printf "${BLUE} ➜  Installing FZF...${NORMAL}\n"
+if [ "$OSTYPE" = "cygwin" ]; then
+    if ! command -v fzf >/dev/null 2>&1 && command -v apt-cyg >/dev/null 2>&1; then
+        apt-cyg install fzf fzf-zsh fzf-zsh-completion
+    fi
+else
+    if [ "$SYSTEM" = "Darwin" ]; then
+        sync_brew_package fzf
+        FZF=/usr/local/opt/fzf
+    elif [ "$SYSTEM" = "Linux" ] && command -v apt-get >/dev/null 2>&1; then
+        sync_repo junegunn/fzf $FZF
+    fi
+    [ -f $FZF/install ] && $FZF/install --all --no-update-rc --no-bash --no-fish >/dev/null
+fi
 
 # Brew
 if [ "$SYSTEM" = "Darwin" ]; then
